version: "3.4"
services:
  web:
    build:
      context: .
      target: web
    restart: unless-stopped
    ports:
      - 0.0.0.0:${BIND_PORT:-8000}:8000
    env_file:
      - .env
    volumes:
      - ./db.sqlite3:/var/app/db.sqlite3
  cron:
    build:
      context: .
      target: cron
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./db.sqlite3:/var/app/db.sqlite3
