version: "3.4"
services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - 127.0.0.1:${BIND_PORT:-8000}:8000
    env_file:
      - .env
    volumes:
      - db:/var/app/db.sqlite3

volumes:
  db: