# Generated by Django 3.1.1 on 2020-09-18 15:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('caller_hint', models.CharField(max_length=100)),
                ('backup_number', models.CharField(max_length=100)),
                ('match_time', models.DateTimeField()),
                ('matched', models.BooleanField()),
                ('goodbye_time', models.DateTimeField()),
                ('goodbye_sent', models.BooleanField()),
                ('registered_notification', models.TextField(default='Registered!')),
                ('match_notification_calling', models.TextField(default='Matched with {phone_number}! Please call')),
                ('match_notification_called', models.TextField(default='Matched with {phone_number}! You will be called')),
                ('goodbye_notification', models.TextField(default='Thanks for participating!')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.group')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=100)),
                ('can_call', models.BooleanField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='match.group')),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='match.match')),
            ],
        ),
    ]
